### ISSUE TITLE
Make Paperbots properly CT/CI-able

### ISSUE THREAD

**Issue by badlogic** [badlogic/paperbots#66]

**Comment by mbrugger** [comment]
How do you deploy the application at the moment? (you mentioned docker-compose in the PR)
I was not able to find any Dockerfiles in the repository.

A setup I use for webapps at the moment is one container based on nginx for serving all static content, and a second one running the java based webservice.

In addition I could imagine to use git flow for organising the deployments. e.g. every push to master deploys the "production" environment while develop is kept in sync with a staging environment.

Automating the deployments should not be that hard. (using travis/dockerhub)

**Comment by badlogic** [comment]
The Dockerfiles aren't in the repository as they contain some passwords (yes, I know...). With one of the recent commits, that has almost changed, save for the MySQL credentials, for which I need to find a solution. Once I've resolved that, I'll add a `docker/` folder here with the `docker-compose.yml` along with the `Dockerfile` for the java server.

The way things are currently setup:

1. I have a Hetzner server that serves all my websites.
2. Each website is a set of containers defined via docker-compose.
3. In front of all those containers sits a single Nginx container that a) makes sure SSL certs are created and renewed and b) forwards to the relevant container based on the incoming request domain.
4. The Paperbots containers are
   1. An Nginx container that logs requests and errors to files in a persistent volume, and forwards all requests to the Java server (including requests for static files).
   2. A MySQL container. The data files are mapped to a persistent volume.
   3. The Java server container, which is stateless. The configuration of the server (email credentials, db credentials), comes from a `.json` file mapped into the container.

Here's the `docker-compose.yml` for the entire site, with MySQL credentials redacted.

```yaml
version: "3"
services:
    web:
        image: nginx:1.13.12
        container_name: paperbots_nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./data/web:/www
            - ./data/logs:/logs
        environment:
            VIRTUAL_HOST: paperbots.io,www.paperbots.io
            LETSENCRYPT_HOST: paperbots.io,www.paperbots.io
            LETSENCRYPT_EMAIL: "badlogicgames@gmail.com"
    site:
        build:
            dockerfile: Dockerfile.site
            context: .
        container_name: paperbots_site
        restart: always
        volumes:
            - ./paperbots.json:/etc/paperbots/paperbots.json
        environment:
            PAPERBOTS_CONFIG: /etc/paperbots/paperbots.json
    mysql:
        image: mysql:5.7.22
        container_name: paperbots_mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=XXXXXX
            - MYSQL_DATABASE=paperbots
        volumes:
            - ./data/mysql:/var/lib/mysql
networks:
    default:
        external:
            name: nginx-proxy
```

The Nginx config simply forwards to the Java server.

```lua
server {
    listen 80;
    index index.php index.html;
    server_name www.paperbots.io paperbots.io;
    error_log  /logs/error.log;
    access_log /logs/access.log;
    root /www;

    # Let the nginx-proxy gives us the
    # real ip, see https://github.com/jwilder/nginx-proxy/issues/130
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;
    set_real_ip_from 0.0.0.0/0;

    # Website requests go to the Java app
    # which serves all assets
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host    $host:$server_port;
        proxy_set_header X-Forwarded-Server  $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://site:8001;
    }
}
```

For the Java server an image is build using the following Dockerfile:

```
FROM openjdk:slim

WORKDIR /

# Curl, git, etc
RUN apt-get update && apt-get -y --force-yes install git maven && \
 	git clone https://github.com/badlogic/paperbots && \
	cd /paperbots/server && mvn clean package -Dmaven.test.skip=true -DskipTests

CMD cd /paperbots/server && ./start.sh
```

This clones the repo, builds a single `.jar`, then starts the server by invoking the `start.sh` script.

If you feel like screaming, you can have a look at the [`start.sh` script](https://github.com/badlogic/paperbots/blob/master/server/start.sh). It's an endless loop that:

1. Pulls in the latest changes from Git
2. Compiles the server `.jar`
3. Executes the `.jar` passing it the config file and the location of the static files.

You might wonder why I build the `.jar` as part of the `Dockerfile.site`. Welp, that will cache the `$HOME/.m2` local Maven repository. Subsequent builds via the `start.sh` file only pull in artifacts that were added to the server's dependencies, or artifacts for which I changed the version in the pom.

This frankenstein the "runs" and serves all request and runs as long as I do not need to change any of the Docker related configuration.

To deploy changes to the frontend code, I have another Frankenstein script called [`publish.sh`](https://github.com/badlogic/paperbots/blob/master/server/publish.sh). As you can see, it commits and pushes my local changes, then calls the [`api/reloadstatic` endpoint](https://github.com/badlogic/paperbots/blob/master/server/src/main/java/io/paperbots/Server.java#L75) of the server. This will trigger a git pull server side, which pulls in the new front end file changes. Nothing needs to get restarted, the server will just serve the new files.

To deploy changes to the backend code, see the [`reload.sh` script](https://github.com/badlogic/paperbots/blob/master/server/reload.sh). It is analogous to the `publish.sh` script, but calls a [different endpoint](https://github.com/badlogic/paperbots/blob/master/server/src/main/java/io/paperbots/Server.java#L83).  That endpoint will shut the server down, which gives back control to the loop in the `start.sh` script.

The next loop iteration pulls in the latest changes from Git, recompiles the Java server, and starts it up again.

Yes, this is a bit insane. But I was/am short on time, and as a single person effort this was the quickest thing I could whip up while mostly keeping my sanity.

My ideal would be to have some sort of blue/green deployment. Build and test a Docker image, tell the Hetzner to fetch the new image and redeploy (gracefully). I know all the pieces of this puzzle **except** what tool I could use to listen to new images in the repository, pulling them in and redeploying them (hence my Frankenstein script approach above).

Since I have a weekly deadline to get new features into Paperbots for the classes I give each Friday, I currently focus more on the feature side than on the "sane CI/CD" side. I'd be grateful for any suggestions regarding the CI/CD story! I won't be able to get to implementing them until after mid December though :/
